---
- hosts: Bastions_Servers
  become: false
  tasks:
    - name: Desplegando el servicio
      shell: |
        echo "Desplegando Declaratoria Service"
        /opt/sinpad/prod/scripts/deploydeeservice.sh
